### ISSUE TITLE
Error while trying to access /status page

### ISSUE THREAD

**Issue by khaledkbadr** [AppScale/appscale#2284] opened 2017-01-23 10:29 UTC
I get this error when trying to access /status page
```
ImportError: No module named http.client
INFO     2017-01-23 10:24:10,992 server.py:580] default: "POST /apps/json/appscaledashboard HTTP/1.0" 500 -
ERROR    2017-01-23 10:24:11,198 wsgi.py:219] 
Traceback (most recent call last):
  File "/root/appscale/AppServer/google/appengine/runtime/wsgi.py", line 196, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/root/appscale/AppServer/google/appengine/runtime/wsgi.py", line 255, in _LoadHandler
    handler = __import__(path[0])
  File "/var/apps/appscaledashboard/app/dashboard.py", line 37, in <module>
    from app_dashboard_helper import AppDashboardHelper
  File "/var/apps/appscaledashboard/app/lib/app_dashboard_helper.py", line 10, in <module>
    import SOAPpy
  File "/var/apps/appscaledashboard/app/vendor/SOAPpy/__init__.py", line 5, in <module>
    from Client      import *
  File "/var/apps/appscaledashboard/app/vendor/SOAPpy/Client.py", line 61, in <module>
    from Parser      import parseSOAPRPC
  File "/var/apps/appscaledashboard/app/vendor/SOAPpy/Parser.py", line 10, in <module>
    from wstools.XMLname import fromXMLname
  File "/var/apps/appscaledashboard/app/vendor/wstools/__init__.py", line 6, in <module>
    from . import WSDLTools  # noqa
  File "/var/apps/appscaledashboard/app/vendor/wstools/WSDLTools.py", line 21, in <module>
    from .Utility import Collection, CollectionNS, DOM, ElementProxy, basejoin  # noqa
  File "/var/apps/appscaledashboard/app/vendor/wstools/Utility.py", line 53, in <module>
    from http.client import HTTPConnection, HTTPSConnection, _CS_REQ_SENT
ImportError: No module named http.client
INFO     2017-01-23 10:24:11,202 server.py:580] default: "POST /apps/json/guestbookgo HTTP/1.0" 500 -
ERROR    2017-01-23 10:24:11,401 wsgi.py:219] 
Traceback (most recent call last):
  File "/root/appscale/AppServer/google/appengine/runtime/wsgi.py", line 196, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/root/appscale/AppServer/google/appengine/runtime/wsgi.py", line 255, in _LoadHandler
    handler = __import__(path[0])
  File "/var/apps/appscaledashboard/app/dashboard.py", line 37, in <module>
    from app_dashboard_helper import AppDashboardHelper
  File "/var/apps/appscaledashboard/app/lib/app_dashboard_helper.py", line 10, in <module>
    import SOAPpy
  File "/var/apps/appscaledashboard/app/vendor/SOAPpy/__init__.py", line 5, in <module>
    from Client      import *
  File "/var/apps/appscaledashboard/app/vendor/SOAPpy/Client.py", line 61, in <module>
    from Parser      import parseSOAPRPC
  File "/var/apps/appscaledashboard/app/vendor/SOAPpy/Parser.py", line 10, in <module>
    from wstools.XMLname import fromXMLname
  File "/var/apps/appscaledashboard/app/vendor/wstools/__init__.py", line 6, in <module>
    from . import WSDLTools  # noqa
  File "/var/apps/appscaledashboard/app/vendor/wstools/WSDLTools.py", line 21, in <module>
    from .Utility import Collection, CollectionNS, DOM, ElementProxy, basejoin  # noqa
  File "/var/apps/appscaledashboard/app/vendor/wstools/Utility.py", line 53, in <module>
    from http.client import HTTPConnection, HTTPSConnection, _CS_REQ_SENT
ImportError: No module named http.client
INFO     2017-01-23 10:24:11,407 server.py:580] default: "POST /apps/json/mobicagecloudhr HTTP/1.0" 500 -
```

**Comment by FastGeert** [comment] 2017-01-23 10:39
Hey Guys, just want to mention that Khaled is working from our Green IT Globe team in Cairo.

**Comment by khaledkbadr** [comment] 2017-01-23 11:46
Error was in `from httplib import FakeSocket`, the `appengine/dist27/httplib.py` didn't have the `FakeSocket` module

**Comment by cdonati** [comment] 2017-01-23 18:18
Hi @khaledkbadr. The dashboard issue was caused by an update to wstools. We did not pin that package to a specific version, so the 3.1.0 install script always attempts to install the latest one.

The issue has been fixed in the install script for the latest master, but you can fix the issue on your existing installation by running these commands and restarting AppScale.

```
APPSCALE_HOME=/root/appscale
rm -rf ${APPSCALE_HOME}/AppDashboard/vendor
pip install -t ${APPSCALE_HOME}/AppDashboard/vendor wstools==0.4.3
pip install -t ${APPSCALE_HOME}/AppDashboard/vendor SOAPpy
pip install -t ${APPSCALE_HOME}/AppDashboard/vendor python-crontab
````

**Closed** 2017-03-02 08:23 UTC
